### ISSUE TITLE
"Message PlaceTileMessage hasn't been handled by ActionPhase phase" error

### ISSUE THREAD

**Issue by Vartigan** [farin/JCloisterZone#272] opened 2018-09-26 18:42 UTC
Hi! We have this error about 7 times.
[error.log](https://github.com/farin/JCloisterZone/files/2421059/error.log)  friend's
[error.log](https://github.com/farin/JCloisterZone/files/2421101/error.log)  mine
I also have saved game with such error 
[errorgame.txt](https://github.com/farin/JCloisterZone/files/2421116/errorgame.txt)  (renamed .jcz to .txt)
Any advice?

**Comment by deadlocker8** [comment] 2018-10-14 20:03
I experienced this error a few times too.

**Comment by KrzysztofMadejski** [comment] 2020-04-12 19:14
I'm getting the same now at 2020. @farin  could you at least tell what you think the error is and what should be fixed?

```
[Thread-1] WARN com.jcloisterzone.game.GameStatePhaseReducer - Unhandled message:
	{"type":"PLACE_TILE","payload":{"gameId":"e6mUT7Y18Z1OU9ckL12G+O9Eebve","messageId":"1.1","tileId":"BA.Rr","rotation":"R0","position":[6,4]}}
[Thread-1] ERROR com.jcloisterzone.ui.Client - Message PlaceTileMessage hasn't been handled by ActionPhase phase.
java.lang.IllegalArgumentException: Message PlaceTileMessage hasn't been handled by ActionPhase phase.
	at com.jcloisterzone.game.GameStatePhaseReducer.applyMessageOnPhase(GameStatePhaseReducer.java:155)
	at com.jcloisterzone.game.GameStatePhaseReducer.apply(GameStatePhaseReducer.java:170)
	at com.jcloisterzone.game.Game.start(Game.java:378)
	at com.jcloisterzone.ui.ClientMessageListener.handleGameStarted(ClientMessageListener.java:223)
	at com.jcloisterzone.ui.ClientMessageListener.handleGame(ClientMessageListener.java:300)
	at com.jcloisterzone.ui.ClientMessageListener.handleGame(ClientMessageListener.java:248)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:38)
	at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:21)
	at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:137)
	at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:106)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:376)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:159)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Nickyes** [comment] 2020-04-20 22:25
Me and our friends have experienced this issue multiple time. Even with last version 4.4.2

[Thread-1] WARN com.jcloisterzone.game.GameStatePhaseReducer - Unhandled message:
	{"type":"PLACE_TILE","payload":{"gameId":"6SlNN9wWT4pQa5CgC3Qa1k61/NBw","messageId":"1.1","tileId":"AM.C++","rotation":"R0","position":[-1,8]}}
[Thread-1] ERROR com.jcloisterzone.ui.Client - Message PlaceTileMessage hasn't been handled by ActionPhase phase.
java.lang.IllegalArgumentException: Message PlaceTileMessage hasn't been handled by ActionPhase phase.
	at com.jcloisterzone.game.GameStatePhaseReducer.applyMessageOnPhase(GameStatePhaseReducer.java:155)
	at com.jcloisterzone.game.GameStatePhaseReducer.apply(GameStatePhaseReducer.java:170)
	at com.jcloisterzone.game.Game.start(Game.java:378)
	at com.jcloisterzone.ui.ClientMessageListener.handleGameStarted(ClientMessageListener.java:223)
	at com.jcloisterzone.ui.ClientMessageListener.handleGame(ClientMessageListener.java:300)
	at com.jcloisterzone.ui.ClientMessageListener.handleGame(ClientMessageListener.java:248)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:38)
	at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:21)
	at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:137)
	at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:106)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:376)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:159)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
	at java.base/java.lang.Thread.run(Thread.java:830)
[Thread-1] WARN com.jcloisterzone.ui.ClientMessageListener - No controller for message CLIENT_UPDATE
[Thread-1] WARN com.jcloisterzone.ui.ClientMessageListener - No controller for message CLIENT_UPDATE

**Comment by ClubEdNZ** [comment] 2020-04-28 08:11
Same as Vartigan's save file, there's no commit action on the first tile placement, but it only comes up as an error in later turns - or maybe if there's a connection error and it tries to reload the game. Here's the save, which gives that exact error if you try to load it. I'd appreciate if anyone can figure out how to edit the file safely to bypass the error and continue the game..

`{"gameId":"IDfSeUedtRb1tZa+pIjcjFYQrKHN","name":"Ed's game","appVersion":"4.4.2","initialSeed":-9067190478925617154,"created":"2020-04-28T18:09:26.908Z","slots":[{"number":2,"serial":1791,"clientId":"u28bn903m117lp8v8m1kj3n4k6","nickname":"Ed"},{"number":3,"serial":22161,"clientId":"a1qvsas7k6c10brk2f55058gmq","nickname":"Tommy"}],"clocks":[19346,90095],"setup":{"expansions":{"BASIC":1,"INNS_AND_CATHEDRALS":1,"ABBEY_AND_MAYOR":1,"TRADERS_AND_BUILDERS":1,"RIVER":1},"rules":{"PIG_HERD_ON_GQ_FARM":true,"RANDOM_SEATING_ORDER":true,"MORE_TUNNEL_TOKENS":true,"TUNNELIZE_ALL_EXPANSIONS":true},"capabilities":["Builder","Cathedral","River","StandardGame","Mayor","BigFollower","TradeGoods","Inn","Abbey","Barn","PigHerd","Wagon","Pig"]},"replay":[{"type":"PLACE_TILE","payload":{"tileId":"R1.LIRI","rotation":"R0","position":[1,0]}},{"type":"PLACE_TILE","payload":{"tileId":"IC.CFR","rotation":"R180","position":[4,1]}},{"type":"PASS","payload":{}},{"type":"COMMIT","payload":{"salt":1588053797659}},{"type":"PLACE_TILE","payload":{"tileId":"IC.RFr.i","rotation":"R0","position":[-1,-1]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[-1,-1],"location":"WE"},"meepleId":"1.small.5"}},{"type":"COMMIT","payload":{"salt":1588053821424}},{"type":"PLACE_TILE","payload":{"tileId":"AM.CCRR","rotation":"R0","position":[4,0]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[4,0],"location":"E"},"meepleId":"0.small.5"}},{"type":"COMMIT","payload":{"salt":1588053825613}},{"type":"PLACE_TILE","payload":{"tileId":"BA.RrC","rotation":"R0","position":[0,5]}},{"type":"PASS","payload":{}},{"type":"COMMIT","payload":{"salt":1588053842683}},{"type":"PLACE_TILE","payload":{"tileId":"IC.CRcR+","rotation":"R270","position":[4,-1]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[4,-1],"location":"NS"},"meepleId":"0.small.3"}},{"type":"COMMIT","payload":{"salt":1588053864161}},{"type":"PLACE_TILE","payload":{"tileId":"BA.Cc.1","rotation":"R0","position":[7,3]}},{"type":"PASS","payload":{}},{"type":"COMMIT","payload":{"salt":1588053869875}},{"type":"PLACE_TILE","payload":{"tileId":"TB.CcR.c","rotation":"R270","position":[7,2]}},{"type":"PASS","payload":{}},{"type":"COMMIT","payload":{"salt":1588053875619}},{"type":"PLACE_TILE","payload":{"tileId":"TB.CcCC.c","rotation":"R180","position":[4,-2]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[4,-2],"location":"SE"},"meepleId":"0.builder.1"}},{"type":"COMMIT","payload":{"salt":1588053891233}},{"type":"PLACE_TILE","payload":{"tileId":"BA.CRRR","rotation":"R270","position":[5,-2]}},{"type":"PASS","payload":{}},{"type":"COMMIT","payload":{"salt":1588053896912}},{"type":"PLACE_TILE","payload":{"tileId":"TB.RRC","rotation":"R270","position":[7,1]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[7,1],"location":"W"},"meepleId":"0.mayor.1"}},{"type":"COMMIT","payload":{"salt":1588053913144}},{"type":"PLACE_TILE","payload":{"tileId":"AM.A","rotation":"R0","position":[6,1]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[6,1],"location":"CLOISTER"},"meepleId":"1.small.6"}},{"type":"COMMIT","payload":{"salt":1588053916951}},{"type":"PLACE_TILE","payload":{"tileId":"TB.Ccc.g","rotation":"R0","position":[3,-2]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[3,-2],"location":"_S"},"meepleId":"0.small.3"}},{"type":"COMMIT","payload":{"salt":1588053938065}},{"type":"PLACE_TILE","payload":{"tileId":"AM.CRr","rotation":"R180","position":[4,-3]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[4,-3],"location":"S"},"meepleId":"1.small.3"}},{"type":"COMMIT","payload":{"salt":1588053957056}},{"type":"PASS","payload":{}},{"type":"COMMIT","payload":{"salt":1588053960593}},{"type":"PLACE_TILE","payload":{"tileId":"BA.Cc.1","rotation":"R0","position":[2,6]}},{"type":"PASS","payload":{}},{"type":"COMMIT","payload":{"salt":1588053980149}},{"type":"PLACE_TILE","payload":{"tileId":"BA.RFr","rotation":"R0","position":[-2,-1]}},{"type":"PASS","payload":{}},{"type":"COMMIT","payload":{"salt":1588053986703}},{"type":"PASS","payload":{}},{"type":"COMMIT","payload":{"salt":1588053992746}},{"type":"PLACE_TILE","payload":{"tileId":"BA.RRRR","rotation":"R0","position":[-1,4]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[-1,4],"location":"E"},"meepleId":"0.small.5"}},{"type":"COMMIT","payload":{"salt":1588054005825}},{"type":"PLACE_TILE","payload":{"tileId":"TB.CCc.c","rotation":"R0","position":[-1,2]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[-1,2],"location":"WE"},"meepleId":"1.small.3"}},{"type":"COMMIT","payload":{"salt":1588054031951}},{"type":"PASS","payload":{}},{"type":"COMMIT","payload":{"salt":1588054035241}},{"type":"PLACE_TILE","payload":{"tileId":"BA.Rr","rotation":"R90","position":[1,-1]}},{"type":"DEPLOY_MEEPLE","payload":{"pointer":{"position":[1,-1],"location":"NR.EL.ER.SL.SR.WL"},"meepleId":"0.small.5"}},{"type":"COMMIT","payload":{"salt":1588054051281}}]}`

**Comment by farin** [comment] 2020-04-28 08:58
@ClubEdNZ unfortunatelly game is corrupted. 
This was happen whan played online, undo used and game was interrupted.
Only save before interrupted game should be helputl
I redeployed new server today which hopefully won't corrupt games anyway.

**Comment by Nickyes** [comment] 2020-04-28 10:23
Sorry, @farin ... so the reason of this problem is when player use the undo feature? I've noticed that happens with the Bazaar tiles, (maybe one of these) it isn't?

**Comment by farin** [comment] 2020-04-28 12:38
@Nickyes I can't say what is source of current report. But what I recently dicovered is bug described above which caused same behavior.

When you played online and used undo then game backup on server side was corrupted. On client everything was ok, so until you leave game and reconnect back nothing bad happened.
But once your leave and resume (or your connection was interrupted) then game tried to load corrupted save from server.

This is bug in 4.4.2 (and earlier) bud I hope it can be workrounded on play server. Which I did in "big server update" which is running on production from today.
If nothing bad happened I hope this will be fixed (at least this one particular bug, there can be still another). 
("big server upgrade" is also about porting server to different framework so this can go bad in different way.)

**Comment by farin** [comment] 2020-04-28 12:53
On deeper level, this error happens anytime when game engine receive wrong sequence of player actions. So it  in common it can be corrupted save or lost/doubled message on network.
(there are some mechanism to prevent lost/doubled message but they can be flawed)

In general you shouldn't see such message when playing only hot seat game on local. 
And undo related bug should neither happen for direct connect.

**Comment by farin** [comment] 2020-04-30 07:01
should be resolved with currently deployed server.

**Comment by KrzysztofMadejski** [comment] 2020-04-30 18:11
Re "When you played online and used undo then game backup on server side was corrupted". How does undo works? It sounds as it deletes last state from the server. In distributed system it should not happen as the state could already been propagated. It should be another action that reverts previous and is placed on top of the stack.

BTW: Is the "play server" another codebase, or this one but differently invoked?

**Comment by farin** [comment] 2020-05-01 07:27
Play server is different codebase.
Game is represented as list of user actions and undo drops action from top.

**Comment by reputet** [comment] 2020-05-31 22:30
> 
> 
> should be resolved with currently deployed server.

Unfortunately, this happened to me despite the redeployed server.

I and three other players were enjoying the game online two evenings in a raw (30 and 31 of May) when the `java.lang.IllegalArgumentException: Message PlaceTileMessage hasn't been handled by ActionPhase phase` exception appeared both times and we weren't able to proceed. It was preceded by several `NullPointerException` which reloaded the game (the map refreshed), but the game state always recovered. I can't be sure which is the cause and which is the effect (NullPointerException and PlaceTileMessage), but let me refer to #297 there too.

The created game still hangs for me in the online games list and that's how my attempt to continue looks like
![image](https://user-images.githubusercontent.com/12900980/83363627-84b9fe80-a3a3-11ea-8cd8-519fc0d6a98d.png)
![image](https://user-images.githubusercontent.com/12900980/83363567-107f5b00-a3a3-11ea-9d6f-22852ae494fb.png)

@farin, we really relish the quality of your work. I hope the provided logs will help you to keep it in the stable shape.
[error.log](https://github.com/farin/JCloisterZone/files/4708552/error.log)
[saved_game.txt](https://github.com/farin/JCloisterZone/files/4708553/saved_game.txt) (originally saved_game.jcz)

**Comment by farin** [comment] 2020-06-01 10:28
@reputet please don't remove game for a while. I will take snapshot of relalated data in server database and maybe can also fix it

**Comment by farin** [comment] 2020-06-01 11:11
saving here important part from game log

```
1) "{\"type\":\"PLACE_TILE\",\"payload\":{\"gameId\":\"tJprSXu3Jh5oZTUYodNmKbn1iGml\",\"tileId\":\"IC.RFr.i\",\"rotation\":\"R0\",\"position\":[4,-2],\"clock\":0,\"messageId\":\"36037983-5be1-4a5d-8938-3b46675711cb\",\"parentId\":\"1ebab062-3f5b-452f-9df5-a89dacc840b5\"}}"
2) "{\"type\":\"PLACE_TILE\",\"payload\":{\"gameId\":\"tJprSXu3Jh5oZTUYodNmKbn1iGml\",\"tileId\":\"IC.RFr.i\",\"rotation\":\"R0\",\"position\":[4,-2],\"clock\":0,\"messageId\":\"1ebab062-3f5b-452f-9df5-a89dacc840b5\",\"parentId\":\"851fca03-0de7-45b5-a802-9008da6850f9\"}}"
3) "{\"type\":\"PLACE_TILE\",\"payload\":{\"gameId\":\"tJprSXu3Jh5oZTUYodNmKbn1iGml\",\"tileId\":\"IC.RFr.i\",\"rotation\":\"R0\",\"position\":[4,-2],\"clock\":0,\"messageId\":\"851fca03-0de7-45b5-a802-9008da6850f9\"}}"
4) "{\"type\":\"COMMIT\",\"payload\":{\"gameId\":\"tJprSXu3Jh5oZTUYodNmKbn1iGml\",\"salt\":1590948736606,\"clock\":0,\"messageId\":\"9b0ed654-4c00-447a-a793-959706e97d26\",\"parentId\":\"7072934e-4b0e-46bf-ada1-425e553be1bc\"}}"
```

**Comment by farin** [comment] 2020-06-01 11:15
@reputet you can try to continue game on server now (i dropped invalid items from game record) or feel free to drop game now

**Comment by farin** [comment] 2020-06-01 13:34
Anyway I put better logging to server. So if this happen again. please report it agian (I need game id which I can get from saved game) 
I was able to see actual result in game state at server side am still not sure how exactly this happened (and new logging should reveal this)

I also added some recovery on client, so hopefully 4.6.1 will be immune even if this happens (showing only warning instead of crash) I will release 4.6.1 during week.

**Comment by reputet** [comment] 2020-06-01 18:22
@farin, thanks for the immediate response!

> @reputet you can try to continue game on server now (i dropped invalid items from game record) or feel free to drop game now

I opened it and the game (along with the map) loaded without any exceptions now. Chances are that we will continue the game later, I'll keep it for a while.

> So if this happen again. please report it agian

No problem.

I'm not sure if my friends will be willing to take a risk of losing the game state again though. They were delighted by the application but disappointed by the inability to restore when it broke.

If we continue and it drops again, I'll report it there.

@farin, please let me know if there is anything else I can help you with.

**Comment by farin** [comment] 2020-06-01 20:55
@repulte
Sorry for that, losing game state is annoying not doubt.

I just update server and put piece of code there which should identify reported issue before broke all (and log it internally). So hopefully it not happen even with current client (and with upcoming 4.6.1 it should be even more safe.

**Comment by farin** [comment] 2020-06-01 20:57
closing due to patched server and 4.6.1 fix, reopen if does not help

**Closed by farin** 2020-06-01 20:57 UTC
Labels: bug, play.jcz, possibly-fixed

**Comment by reputet** [comment] 2020-06-02 00:56
Thanks, @farin!

I hope I'll give it a try this week. I'll let you know if something happens.

**Comment by farin** [comment] 2020-06-02 10:43
@reputet 4.6.1 is out. Thanks for your report, It directed me to right place and I believe I found root cause and this nasty synchronization issue is now gone. (And if not 4.6.1 should be able to recover it  anyway)
